const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('abdx', {
  systemStatus: () => ipcRenderer.invoke('system:status'),
  models: () => ipcRenderer.invoke('ollama:models'),
  modelProfile: () => ipcRenderer.invoke('models:profile'),
  modelPlan: () => ipcRenderer.invoke('models:plan'),
  modelPull: (model) => ipcRenderer.invoke('models:pull', model),
  modelStop: (model) => ipcRenderer.invoke('models:stop', model),
  resourceStatus: () => ipcRenderer.invoke('resources:status'),
  resourcePreflight: (payload={}) => ipcRenderer.invoke('resources:preflight', payload),
  intelligenceStatus: () => ipcRenderer.invoke('intelligence:status'),
  intelligencePlan: (payload={}) => ipcRenderer.invoke('intelligence:plan', payload),
  dagStatus: () => ipcRenderer.invoke('dag:status'),
  dagCancel: (runId) => ipcRenderer.invoke('dag:cancel', runId),
  transactionsStatus: (workspace='') => ipcRenderer.invoke('transactions:status', workspace),
  transactionDiff: (payload={}) => ipcRenderer.invoke('transactions:diff', payload),
  transactionPreviewFile: (payload={}) => ipcRenderer.invoke('transactions:previewFile', payload),
  transactionRollback: (payload={}) => ipcRenderer.invoke('transactions:rollback', payload),
  worktreesStatus: () => ipcRenderer.invoke('worktrees:status'),
  worktreePreview: (id) => ipcRenderer.invoke('worktrees:preview', id),
  lanesStatus: () => ipcRenderer.invoke('lanes:status'),
  laneBundlePreview: (id) => ipcRenderer.invoke('lanes:preview', id),
  evaluationsStatus: () => ipcRenderer.invoke('evaluations:status'),
  evaluationsRun: (payload={}) => ipcRenderer.invoke('evaluations:run', payload),
  evaluationsPromoteBaseline: (runId='') => ipcRenderer.invoke('evaluations:promoteBaseline', runId),
  apiStatus: () => ipcRenderer.invoke('api:status'),
  rotateApiKey: () => ipcRenderer.invoke('api:rotateKey'),
  selectFolder: () => ipcRenderer.invoke('dialog:selectFolder'),
  selectFiles: () => ipcRenderer.invoke('dialog:selectFiles'),
  inspectFile: (filePath) => ipcRenderer.invoke('file:inspect', filePath),
  compareFiles: (paths) => ipcRenderer.invoke('file:compare', paths),
  knowledgeStatus: () => ipcRenderer.invoke('knowledge:status'),
  knowledgeIndex: (paths) => ipcRenderer.invoke('knowledge:index', paths),
  knowledgeSearch: (query) => ipcRenderer.invoke('knowledge:search', query),
  knowledgeClear: () => ipcRenderer.invoke('knowledge:clear'),
  memoryStatus: (project='') => ipcRenderer.invoke('memory:status', project),
  memoryList: (payload={}) => ipcRenderer.invoke('memory:list', payload),
  memorySearch: (payload={}) => ipcRenderer.invoke('memory:search', payload),
  memoryAdd: (payload={}) => ipcRenderer.invoke('memory:add', payload),
  memoryDelete: (id) => ipcRenderer.invoke('memory:delete', id),
  memoryClearProject: (project='') => ipcRenderer.invoke('memory:clearProject', project),
  researchStatus: () => ipcRenderer.invoke('research:status'),
  researchRun: (payload) => ipcRenderer.invoke('research:run', payload),
  browseResearchUrl: (url) => ipcRenderer.invoke('research:browse', url),
  agentsStatus: () => ipcRenderer.invoke('agents:status'),
  skillsList: () => ipcRenderer.invoke('skills:list'),
  skillsReload: () => ipcRenderer.invoke('skills:reload'),
  mcpStatus: () => ipcRenderer.invoke('mcp:status'),
  mcpAddServer: (server) => ipcRenderer.invoke('mcp:addServer', server),
  mcpRemoveServer: (name) => ipcRenderer.invoke('mcp:removeServer', name),
  mcpListTools: (name) => ipcRenderer.invoke('mcp:listTools', name),
  mcpOpenConfig: () => ipcRenderer.invoke('mcp:openConfig'),
  integrationsStatus: (options={}) => ipcRenderer.invoke('integrations:status', options),
  integrationsQuery: (payload={}) => ipcRenderer.invoke('integrations:query', payload),
  integrationsPropose: (payload={}) => ipcRenderer.invoke('integrations:propose', payload),
  integrationsApprovals: () => ipcRenderer.invoke('integrations:approvals'),
  integrationsApprove: (id) => ipcRenderer.invoke('integrations:approve', id),
  integrationsReject: (id) => ipcRenderer.invoke('integrations:reject', id),
  integrationsAudit: (limit=100) => ipcRenderer.invoke('integrations:audit', limit),
  workflowsList: () => ipcRenderer.invoke('workflows:list'),
  workflowGet: (id) => ipcRenderer.invoke('workflows:get', id),
  workflowCreate: (payload={}) => ipcRenderer.invoke('workflows:create', payload),
  workflowStart: (id) => ipcRenderer.invoke('workflows:start', id),
  workflowPause: (id) => ipcRenderer.invoke('workflows:pause', id),
  workflowResume: (id) => ipcRenderer.invoke('workflows:resume', id),
  workflowRetry: (id) => ipcRenderer.invoke('workflows:retry', id),
  workflowCancel: (id) => ipcRenderer.invoke('workflows:cancel', id),
  workflowDelete: (id) => ipcRenderer.invoke('workflows:delete', id),
  automationsList: () => ipcRenderer.invoke('automations:list'),
  automationGet: (id) => ipcRenderer.invoke('automations:get', id),
  automationCreate: (payload={}) => ipcRenderer.invoke('automations:create', payload),
  automationRunNow: (id) => ipcRenderer.invoke('automations:runNow', id),
  automationSetEnabled: (id,enabled) => ipcRenderer.invoke('automations:setEnabled', {id,enabled}),
  automationDelete: (id) => ipcRenderer.invoke('automations:delete', id),
  runtimeStatus: () => ipcRenderer.invoke('runtime:status'),
  runtimeShow: (mode='') => ipcRenderer.invoke('runtime:show', mode),
  runtimeHide: () => ipcRenderer.invoke('runtime:hide'),
  runtimeSetStartup: (enabled) => ipcRenderer.invoke('runtime:setStartup', enabled),
  runtimePauseScheduler: () => ipcRenderer.invoke('runtime:pauseScheduler'),
  runtimeResumeScheduler: () => ipcRenderer.invoke('runtime:resumeScheduler'),
  runtimeOpenLogs: () => ipcRenderer.invoke('runtime:openLogs'),
  recoveryStatus: () => ipcRenderer.invoke('recovery:status'),
  recoverySessionGet: () => ipcRenderer.invoke('recovery:sessionGet'),
  recoverySessionSave: (payload={}) => ipcRenderer.invoke('recovery:sessionSave', payload),
  recoverySessionClear: () => ipcRenderer.invoke('recovery:sessionClear'),
  recoveryReports: (limit=50) => ipcRenderer.invoke('recovery:reports', limit),
  recoveryOpenReports: () => ipcRenderer.invoke('recovery:openReports'),
  listWorkspace: (root) => ipcRenderer.invoke('workspace:list', root),
  readWorkspaceFile: (root, rel) => ipcRenderer.invoke('workspace:read', { root, rel }),
  writeWorkspaceFile: (root, rel, content) => ipcRenderer.invoke('workspace:write', { root, rel, content }),
  inspectProject: (root) => ipcRenderer.invoke('project:inspect', root),
  startProject: (payload) => ipcRenderer.invoke('project:start', payload),
  stopProject: (root) => ipcRenderer.invoke('project:stop', root),
  projectStatus: (root) => ipcRenderer.invoke('project:status', root),
  projectCheck: (payload) => ipcRenderer.invoke('project:check', payload),
  gitStatus: (root) => ipcRenderer.invoke('git:status', root),
  gitDiff: (root) => ipcRenderer.invoke('git:diff', root),
  gitLog: (root) => ipcRenderer.invoke('git:log', root),
  terminalStart: (payload) => ipcRenderer.invoke('terminal:start', payload),
  terminalWrite: (payload) => ipcRenderer.invoke('terminal:write', payload),
  terminalKill: (id) => ipcRenderer.invoke('terminal:kill', id),
  browserOpenPreview: (payload) => ipcRenderer.invoke('browser:openPreview', payload),
  browserInspect: () => ipcRenderer.invoke('browser:inspect'),
  browserScreenshot: (payload) => ipcRenderer.invoke('browser:screenshot', payload),
  browserRefresh: () => ipcRenderer.invoke('browser:refresh'),
  browserOpenExternal: (url) => ipcRenderer.invoke('browser:openExternal', url),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSave: (patch) => ipcRenderer.invoke('settings:save', patch),
  diagnosticsRun: () => ipcRenderer.invoke('diagnostics:run'),
  diagnosticsExport: () => ipcRenderer.invoke('diagnostics:export'),
  backupCreate: () => ipcRenderer.invoke('backup:create'),
  backupList: () => ipcRenderer.invoke('backup:list'),
  backupRestore: (backupPath) => ipcRenderer.invoke('backup:restore', backupPath),
  backupOpenFolder: () => ipcRenderer.invoke('backup:openFolder'),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  chat: (payload) => ipcRenderer.invoke('assistant:chat', payload),
  saveMarkdown: (body) => ipcRenderer.invoke('report:saveMarkdown', body),
  onTerminalData: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on('terminal:data', handler);
    return () => ipcRenderer.removeListener('terminal:data', handler);
  },
  onProjectEvent: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on('project:event', handler);
    return () => ipcRenderer.removeListener('project:event', handler);
  },
  onAgentEvent: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on('agent:event', handler);
    return () => ipcRenderer.removeListener('agent:event', handler);
  },
  onRuntimeNavigate: (cb) => {
    const handler = (_event, data) => cb(data);
    ipcRenderer.on('runtime:navigate', handler);
    return () => ipcRenderer.removeListener('runtime:navigate', handler);
  }
});
